In [1]:
import pandas as pd
import os

path = os.path.realpath(__name__) # path
drt = os.path.dirname(path)       # directory

# Load the CSV file into a DataFrame
file_path = drt.replace('\\robustness_check', '') + '\\analysis\\VAR' + '/daily_topics_extend_comp_rev_components.csv'
daily_topics = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
daily_topics.head()

,log_ret,date,T0,T1,T2,T3,T4,T5,T6,T7,...,Component1extend,Component2extend,Component3extend,Component4extend,Component5extend,Component6extend,Component7extend,Component8extend,Component9extend,Component10extend
0,0.024653,2016-01-13,0.003758,0.003431,0.004657,0.003350,0.003350,0.003513,0.003268,0.003431,...,0.888262,0.240469,-0.176107,0.013588,0.052418,-0.055451,0.169853,0.196128,0.108359,-0.179799
1,-0.032606,2016-01-14,0.003758,0.003431,0.004657,0.003350,0.003350,0.003513,0.003268,0.003431,...,0.888262,0.240469,-0.176107,0.013588,0.052418,-0.055451,0.169853,0.196128,0.108359,-0.179799
2,0.004484,2016-01-15,0.003758,0.003431,0.004657,0.003350,0.003350,0.003513,0.003268,0.003431,...,0.888262,0.240469,-0.176107,0.013588,0.052418,-0.055451,0.169853,0.196128,0.108359,-0.179799
3,-0.028255,2016-01-18,0.005000,0.002941,0.007941,0.003750,0.004412,0.003529,0.006176,0.035735,...,3.382226,-0.406938,-0.845114,-2.223538,-0.838879,0.277848,-0.609436,-0.277763,0.271941,0.270042
4,0.047632,2016-01-19,0.001509,0.001415,0.038561,0.001415,0.005495,0.001368,0.010425,0.009623,...,0.757738,0.072041,-0.190549,-0.161817,-0.059648,0.028488,-0.006932,0.007548,0.194776,-0.041500

In [2]:
# Load the Excel file into a DataFrame
file_path = 'OSE_Prices.xlsx'
ose = pd.read_excel(file_path)

# Display the first few rows of the DataFrame
ose.head()

  Exchange Date   Close      %Chg  log_ret_OSE
0    2016-01-04  530.60  0.000000     0.000000
1    2016-01-05  520.27 -0.019469    -0.019661
2    2016-01-06  513.35 -0.013301    -0.013390
3    2016-01-07  498.56 -0.028811    -0.029234
4    2016-01-08  496.71 -0.003711    -0.003718

In [3]:
# Ensure that both 'date' columns are in datetime format
daily_topics['date'] = pd.to_datetime(daily_topics['date'])
ose['Exchange Date'] = pd.to_datetime(ose['Exchange Date'])

# Merge the DataFrames on the date columns
# Rename the 'Exchange Date' column to 'date' in the ose DataFrame for merging
ose.rename(columns={'Exchange Date': 'date'}, inplace=True)

# Merge the DataFrames
merged_df = pd.merge(daily_topics, ose[['date', 'log_ret_OSE']], on='date', how='left')

# Display the first few rows of the merged DataFrame
merged_df.head()

,log_ret,date,T0,T1,T2,T3,T4,T5,T6,T7,...,Component2extend,Component3extend,Component4extend,Component5extend,Component6extend,Component7extend,Component8extend,Component9extend,Component10extend,log_ret_OSE
0,0.024653,2016-01-13,0.003758,0.003431,0.004657,0.003350,0.003350,0.003513,0.003268,0.003431,...,0.240469,-0.176107,0.013588,0.052418,-0.055451,0.169853,0.196128,0.108359,-0.179799,0.006355
1,-0.032606,2016-01-14,0.003758,0.003431,0.004657,0.003350,0.003350,0.003513,0.003268,0.003431,...,0.240469,-0.176107,0.013588,0.052418,-0.055451,0.169853,0.196128,0.108359,-0.179799,-0.022423
2,0.004484,2016-01-15,0.003758,0.003431,0.004657,0.003350,0.003350,0.003513,0.003268,0.003431,...,0.240469,-0.176107,0.013588,0.052418,-0.055451,0.169853,0.196128,0.108359,-0.179799,-0.013678
3,-0.028255,2016-01-18,0.005000,0.002941,0.007941,0.003750,0.004412,0.003529,0.006176,0.035735,...,-0.406938,-0.845114,-2.223538,-0.838879,0.277848,-0.609436,-0.277763,0.271941,0.270042,-0.011743
4,0.047632,2016-01-19,0.001509,0.001415,0.038561,0.001415,0.005495,0.001368,0.010425,0.009623,...,0.072041,-0.190549,-0.161817,-0.059648,0.028488,-0.006932,0.007548,0.194776,-0.041500,0.029030

In [4]:
# Save the DF:
save_path = drt.replace('\\robustness_check', '') + '\\analysis\\VAR' + '/daily_topics_extend_comp_rev_components_ose.csv' 
merged_df.to_csv(save_path, index = False)